### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by eliasbrange** [TritonDataCenter/containerpilot#572]
Howdy, just reaching out to see what status there is on the containerpilot project. It has been very quiet in here for many months now. @cheapRoc @tgross

**Comment by cheapRoc** [comment]
Personally, I've moved on and am contributing to other endeavors. Given my own experience, I largely consider ContainerPilot feature complete but would happily continue commenting and contributing outside the code base if it helped folks (as I've done on and offline in the past).

**Comment by untoreh** [comment]
I still experience problems reaping processes on kernel `2.6`, and I wonder if there is room for memory optimizations

**Comment by cheapRoc** [comment]
@untoreh many of the issues involving ContainerPilot end up being associated with the software it is supervising. With that said, I have a project over at [cheapRoc/cp-leaky](https://github.com/cheapRoc/cp-leaky) that can help harvest data used to solve CP memory issues. The idea originated from joyent/containerpilot#464.
